### ISSUE TITLE
Add license to README

### ISSUE THREAD

**Issue by stain** [watchdog-wms/watchdog-wms-workflows#13]
As the workflows in this repository presumably are distributed under GPLv3, users of the repository should be aware of that, as it means if they modify these workflows for their own purposes (including copy-pasting large parts), the modified work must also be licensed as GPLv3 (if distributed).

It is recommended to make it clear to users beyond just having a LICENSE file, to declare the copyright and in particular to confirm that the "or any later version" condition still stands. See <https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly>

I suggest adding to the README something like:

```
    Copyright (C) 2019-2020 Author1/institution1
    Copyright (C) 2019-2020 Author2/institution2
    Copyright (C) 2019-2020 watchdog-wms community contributors

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

This copyright header can also be added as an `<!-- xml comment -->` to each of the workflows.

btw, I think the current GPL3 license makes sense for these workflows, as they are complete and represent intellectual property. For example workflows ("hello world") I would recommend [Creative Commons Zero Public Domain](https://creativecommons.org/share-your-work/public-domain/cc0/) so that no re-attribution or re-licensing is necessary.

See also https://github.com/watchdog-wms/watchdog-wms-modules/issues/89

**Comment by stain** [comment]
btw, for watchdog-wms community contributors you may want to add a `CONTRIBUTORS.txt` file, as the list of organization members in github is not usually public.

**Comment by klugem** [comment]
Thanks for the suggestions.
